#!/usr/bin/env python3
"""make_placeholder_hero.py — Generate a visually-distinct placeholder PNG.

Used during Phase 3 demo when the real keynote video isn't reachable
(e.g. sandbox blocks YouTube / Apple HLS). The generated image is
1920x1080, carries the feature title + an explicit "PLACEHOLDER" banner,
and plugs into build_ppt.py exactly like a real best_0.png would.

Usage:
    make_placeholder_hero.py <out_png> <title_line1> [<title_line2>]
"""
from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


CRIMSON = (139, 26, 26)
LIGHT_GRAY = (244, 244, 244)
DARK_TEXT = (40, 40, 40)
GRID = (220, 220, 220)


def _font(size: int) -> ImageFont.ImageFont:
    for name in (
        "DejaVuSans-Bold.ttf",
        "DejaVuSans.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    ):
        try:
            return ImageFont.truetype(name, size)
        except OSError:
            continue
    return ImageFont.load_default()


def make(out: Path, line1: str, line2: str = "") -> None:
    w, h = 1920, 1080
    img = Image.new("RGB", (w, h), LIGHT_GRAY)
    draw = ImageDraw.Draw(img)

    # Grid background so it feels like a slide mockup, not a blank gray.
    for x in range(0, w, 120):
        draw.line([(x, 0), (x, h)], fill=GRID, width=1)
    for y in range(0, h, 120):
        draw.line([(0, y), (w, y)], fill=GRID, width=1)

    # Crimson top band
    draw.rectangle([0, 0, w, 70], fill=CRIMSON)
    draw.text((40, 18), "PLACEHOLDER · replace with frames/<id>/best_0.png",
              fill="white", font=_font(28))

    # Center big title
    title_font = _font(96)
    sub_font = _font(54)
    tw, th = draw.textbbox((0, 0), line1, font=title_font)[2:]
    draw.text(((w - tw) / 2, h / 2 - th), line1, fill=DARK_TEXT, font=title_font)
    if line2:
        tw2 = draw.textbbox((0, 0), line2, font=sub_font)[2]
        draw.text(((w - tw2) / 2, h / 2 + 30), line2, fill=CRIMSON, font=sub_font)

    # Footer note
    draw.text(
        (40, h - 60),
        "This synthetic tile is generated by make_placeholder_hero.py. "
        "Run extract_frames.py + pick_best_frame.py on a real video.mp4 to replace it.",
        fill=DARK_TEXT, font=_font(22),
    )

    out.parent.mkdir(parents=True, exist_ok=True)
    img.save(out, optimize=True)


def main(argv: list[str]) -> int:
    if len(argv) < 3:
        print(f"Usage: {argv[0]} <out.png> <line1> [<line2>]", file=sys.stderr)
        return 2
    out = Path(argv[1])
    line1 = argv[2]
    line2 = argv[3] if len(argv) >= 4 else ""
    make(out, line1, line2)
    print(f"==> Wrote {out} ({out.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
